**BEGINNER**

In [ ]:

 #1.How do you import the NumPy library using an alias?
import numpy as np

In [ ]:
# 2.How do you check the version and configuration of NumPy?
import numpy as np
np.__version__
np.show_config()

Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc


In [ ]:
# 3.How do you create a vector filled with zeros of size 10?
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# 4.How do you find help/documentation for a NumPy function from the command line?
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [ ]:
# 5.How do you create a zero vector of size 10 with the fifth element as 1?
a=np.zeros(10)
a[4]=1
print(a)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
 #6.How do you create a vector with values from 10 to 49?
 #np.full((40),range(10,50))
 a=np.arange(10,50)
 print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
 #7.How do you reverse a vector?
np.arange(40)[::-1]
#print(a[::-1])

array([39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23,
       22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,
        5,  4,  3,  2,  1,  0])

In [ ]:
# 8.How do you create a 3x3 matrix with values from 0 to 8?
np.arange(9).reshape(3,3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
 #9.How do you find indices of non-zero elements in an array?
 a=[1,4,0,84,00,0,4,5,0,0,0]
 np.nonzero(a)

(array([0, 1, 3, 6, 7]),)

In [ ]:
# 10.How do you create a 3x3 identity matrix?
np.eye(3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# 11.How do you generate a 3x3x3 array with random values?
np.random.random((3,3,3))
np.random.rand(3,3,3)

array([[[0.57256096, 0.12251061, 0.16175721],
        [0.71347401, 0.13748977, 0.3631286 ],
        [0.09132946, 0.82520816, 0.44696476]],

       [[0.53256958, 0.23798289, 0.20210922],
        [0.46574802, 0.10405877, 0.49501117],
        [0.43378873, 0.20369681, 0.82921644]],

       [[0.8093672 , 0.1027265 , 0.96833451],
        [0.24049931, 0.67041032, 0.20377327],
        [0.25862533, 0.53273695, 0.20755756]]])

In [ ]:
# 12.How do you find the min and max values in a 10x10 random matrix?
a=np.random.rand(10,10)
print(a)
print("max:",a.max())
print("min:",a.min())

[[0.37630764 0.02893272 0.88429545 0.49897668 0.98151985 0.7454104
  0.81840812 0.7868756  0.47913935 0.42819348]
 [0.96093511 0.67194386 0.07536599 0.49195034 0.43129488 0.26828226
  0.19431892 0.58777638 0.39941054 0.33479436]
 [0.75250955 0.96325758 0.39610252 0.5353966  0.63984198 0.86759961
  0.62641378 0.58633141 0.13653859 0.96617497]
 [0.16529796 0.761016   0.10276436 0.29897179 0.51114699 0.0334562
  0.20171642 0.87085131 0.0548543  0.8396226 ]
 [0.01200306 0.30477704 0.33077967 0.50466199 0.7207134  0.13362313
  0.55821101 0.10271316 0.42847864 0.47915773]
 [0.82004152 0.39772589 0.20866431 0.21471193 0.68157393 0.43429317
  0.95652815 0.5023166  0.92828889 0.01104506]
 [0.9180348  0.35215886 0.68842231 0.14552825 0.73623387 0.85223789
  0.7176155  0.24071104 0.48220727 0.35808771]
 [0.94181499 0.37181834 0.10526928 0.53388163 0.53687581 0.41763469
  0.03893627 0.0517118  0.00422755 0.5555966 ]
 [0.28775106 0.39018245 0.91998267 0.45475943 0.75822548 0.82394167
  0.54063122 0

In [ ]:
# 13.How do you calculate the mean of a random vector of size 30?
a=np.random.rand(30)
print(a)
print("mean:",a.mean())

[0.07218798 0.14410997 0.61576936 0.49068688 0.57683073 0.37778238
 0.79265361 0.19154996 0.60466843 0.78453792 0.37371144 0.11461261
 0.02575506 0.665584   0.12135192 0.39877836 0.6563923  0.76847355
 0.78676956 0.57805012 0.13827189 0.57336822 0.56791956 0.99128417
 0.32181584 0.24200242 0.55752816 0.85969058 0.78748705 0.08071869]
mean: 0.47534475787454655


In [ ]:
# 14.How do you create a 2D array with 1s on the border and 0s inside?


[[2 2 2 2 2 2 2 2 2 2]
 [2 0 0 0 0 0 0 0 0 2]
 [2 0 0 0 0 0 0 0 0 2]
 [2 0 0 0 0 0 0 0 0 2]
 [2 0 0 0 0 0 0 0 0 2]
 [2 0 0 0 0 0 0 0 0 2]
 [2 0 0 0 0 0 0 0 0 2]
 [2 0 0 0 0 0 0 0 0 2]
 [2 0 0 0 0 0 0 0 0 2]
 [2 2 2 2 2 2 2 2 2 2]]


In [ ]:

# 15.What is the result of operations like 0 * np.nan, np.nan == np.nan, etc.?

False

In [ ]:
# 16.How do you create a matrix with values below the diagonal?
a=np.diag(1+np.arange(3),k=-1)
print(a)

[[0 0 0 0]
 [1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]]


In [ ]:
#17.How do you create a checkerboard pattern in an 8x8 matrix?
a=np.zeros((8,8),dtype=int)
a[1::2,0::2]=1
a[0::2,1::2]=1
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
# 18.How do you find the index of a flat element in a 3D shape?
a=np.arange(1,10).reshape(3,3)

print(a)
a_flat = a.flatten()
print("Flattened array:", a_flat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Flattened array: [1 2 3 4 5 6 7 8 9]


In [ ]:
# 19.How do you create a checkerboard pattern using NumPy's tile function?
a=np.array([[0,1],[1,0]])
print(a)
np.tile(a,(2,2))

[[0 1]
 [1 0]]


array([[0, 1, 0, 1],
       [1, 0, 1, 0],
       [0, 1, 0, 1],
       [1, 0, 1, 0]])

In [ ]:
# 20.How do you normalize a matrix (values between 0 and 1)?
a=np.random.rand(9).reshape(3,3)
print("normal:",a)
normalized=(a-a.min()/(a.max()-a.min()))
print("normalized_matrix:",normalized)


normal: [[0.39473596 0.31090299 0.90534366]
 [0.76181956 0.78389446 0.54993348]
 [0.54432188 0.9425535  0.47579217]]
normalized_matrix: [[-0.09747133 -0.18130431  0.41313637]
 [ 0.26961226  0.29168716  0.05772619]
 [ 0.05211458  0.45034621 -0.01641512]]


In [ ]:
# 21.How do you define a custom data type for storing color (RGBA)?
color_dtype=np.dtype([('r',np.uint8),('g',np.uint8),('b',np.uint8),('a',np.uint8)])
colors=np.array([(1,0,0,255),(0,255,0,255),(0,0,255,255)],dtype=color_dtype)
print(colors)
print(colors[0]['g'])

[(1,   0,   0, 255) (0, 255,   0, 255) (0,   0, 255, 255)]
0


In [ ]:
# 22.How do you perform a matrix multiplication between two matrices?
import numpy as np
a=np.random.rand(9).reshape(3,3)
b=np.random.rand(9).reshape(3,3)
print(a)
print(b)
np.dot(a,b)


[[0.83598276 0.60046551 0.3950324 ]
 [0.13627978 0.53460156 0.54307421]
 [0.42532899 0.35928124 0.7425132 ]]
[[0.51389123 0.59083287 0.4321512 ]
 [0.88925186 0.49263536 0.22524889]
 [0.61468334 0.71851821 0.18025017]]


array([[1.20638912, 1.07357461, 0.5677298 ],
       [0.87924709, 0.73409092, 0.2772011 ],
       [0.99447485, 0.96180225, 0.39857226]])

In [ ]:
# 23.How do you negate values between two given numbers in a vector?


In [ ]:
# 24.What is the output of sum(range(5), -1) vs np.sum(range(5), -1)?
the output of sum(range(5), -1) is:9
the output of np.sum(range(5), -1) is:int64(10)

In [ ]:
# 25.Which NumPy vector operations are legal or illegal?
Legal operations:+,-,*,/,>,<,==,<=,>=,!=
Illegal operations:
converting strings into numbers,
converting numbers into strings,
perform operations on two diff size arrays


In [ ]:

# 26.What happens when you divide integers or floats by zero in NumPy?
zero divisible error will be raised

In [ ]:
# 27.How do you round a float array away from zero?
Z = np.random.uniform(-10, +10, 10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

[  9.   2.   8.   2.  -8. -10.  10.  -1.  -4.   9.]


In [ ]:
# 28.How do you extract the integer part of a float using multiple methods?
print("Using astype(int):", Z.astype(int))

Using astype(int): [ 8  1  7  1 -7 -9  9  0 -3  8]


In [ ]:
# 29.How do you create a 5x5 matrix with row values ranging from 0 to 4?
np.full((5,5),range(5))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [ ]:

# 30.How do you use a generator to create a NumPy array?
def generate():
    for x in range(10):
        yield x
np.fromiter(generate(),dtype=int,count=-1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# 31.How do you create an array with evenly spaced values between 0 and 1 (excluded)?

np.linspace(0,1,11,endpoint=False)[1:]


array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [ ]:
# 32.How do you sort a random array?
a=np.random.rand(10)
print(a)
np.sort(a)

[0.899445   0.58578779 0.21194663 0.73308761 0.74346777 0.84152849
 0.03675285 0.86698741 0.46238214 0.24352942]


array([0.03675285, 0.21194663, 0.24352942, 0.46238214, 0.58578779,
       0.73308761, 0.74346777, 0.84152849, 0.86698741, 0.899445  ])

In [ ]:
# 33.How do you sum an array faster than using np.sum?
a=np.random.rand(100)

%timeit a.sum()
%timeit np.sum(a)


1.98 µs ± 693 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
3.43 µs ± 385 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
# 34.How do you check if two arrays are equal?
a=np.random.rand(10)
b=np.random.rand(10)
print(a)
print(b)
np.array_equal(a,b)

[0.35870963 0.0242177  0.10161538 0.60587814 0.4487627  0.62004841
 0.04693186 0.66335696 0.58753757 0.96150501]
[0.05931596 0.27079018 0.07646841 0.40801764 0.0443909  0.83902989
 0.03460891 0.23786329 0.21179852 0.62160853]


False

In [ ]:
 #35.How do you make a NumPy array read-only?
 a=np.random.rand(10)
 a.flags.writeable=False
 a[0]=1

ValueError: assignment destination is read-only

In [ ]:
#36. How do you convert Cartesian coordinates to polar coordinates?
a=np.random.rand(10,2)
x,y=a[:,0],a[:,1]
r=np.sqrt(x**2+y**2)
t=np.arctan2(y,x)
print(r)
print(t)

[0.956003   0.85890961 0.68926286 0.95695678 0.07233552 1.00193415
 1.35020219 0.98999159 0.85321161 0.58883538]
[1.01665922 0.41872436 1.46766536 0.75944197 0.86681462 1.29880301
 0.83191874 1.22316924 1.27132899 1.13715093]


In [ ]:
#37. How do you replace the maximum value in an array with zero?
import numpy as np
a=np.random.rand(10)
print(a)
print("max value are:",a.max())
a[a.argmax()]=0
print(a)

[0.36418482 0.86538723 0.00968255 0.79858393 0.63858909 0.64940094
 0.48082831 0.74712143 0.70642628 0.95008195]
max value are: 0.9500819529034404
[0.36418482 0.86538723 0.00968255 0.79858393 0.63858909 0.64940094
 0.48082831 0.74712143 0.70642628 0.        ]


In [ ]:
#38. How do you create a structured array for (x, y) coordinate pairs?
import numpy as np
np.zeros(10, [ ('x',int),('y',int)])

array([(0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0),
       (0, 0), (0, 0)], dtype=[('x', '<i8'), ('y', '<i8')])

In [ ]:
#39. How do you create a Cauchy matrix using two arrays?
import numpy as np
x = np.arange(8)
y = x + 0.5
c = 1.0 / np.subtract.outer(x, y)
print(c)


[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222 -0.18181818
  -0.15384615 -0.13333333]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429 -0.22222222
  -0.18181818 -0.15384615]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4        -0.28571429
  -0.22222222 -0.18181818]
 [ 0.4         0.66666667  2.         -2.         -0.66666667 -0.4
  -0.28571429 -0.22222222]
 [ 0.28571429  0.4         0.66666667  2.         -2.         -0.66666667
  -0.4        -0.28571429]
 [ 0.22222222  0.28571429  0.4         0.66666667  2.         -2.
  -0.66666667 -0.4       ]
 [ 0.18181818  0.22222222  0.28571429  0.4         0.66666667  2.
  -2.         -0.66666667]
 [ 0.15384615  0.18181818  0.22222222  0.28571429  0.4         0.66666667
   2.         -2.        ]]


In [ ]:
#40. How do you find the range of values for each NumPy scalar type?
a=np.arange(10)
print(a)
print("min:",a.min())
print("max:",a.max())
print("range:",a.max()-a.min())

[0 1 2 3 4 5 6 7 8 9]
min: 0
max: 9
range: 9


In [ ]:
#41. How do you display all values in a large array?
import numpy as np

large_array = np.random.rand(100).reshape(10, 10)



np.set_printoptions(threshold=np.inf)

print(large_array)

[[0.93040757 0.22579075 0.8722885  0.26051329 0.76425457 0.45014062
  0.29778798 0.23659847 0.90341695 0.01532291]
 [0.21402572 0.32906648 0.05653927 0.93259111 0.33555108 0.83770516
  0.47199434 0.09265962 0.87578387 0.20652532]
 [0.64170206 0.52305103 0.98844809 0.2584504  0.49915828 0.63697531
  0.96885514 0.96187967 0.50497923 0.94400314]
 [0.98125688 0.32022216 0.37145695 0.76666257 0.99866979 0.25508888
  0.98245254 0.30236895 0.86302811 0.35684394]
 [0.01236848 0.94706117 0.59164082 0.65045959 0.13818028 0.55573952
  0.59819752 0.7532756  0.62628357 0.35624364]
 [0.638173   0.88594782 0.75700532 0.45592812 0.97730454 0.79676617
  0.29972281 0.49173311 0.68277661 0.74771042]
 [0.83477665 0.33246317 0.66718582 0.53868304 0.98625896 0.48300722
  0.40959246 0.17774736 0.93252227 0.81629159]
 [0.77439721 0.72991789 0.6622821  0.82129774 0.32879694 0.43290856
  0.99309327 0.69250086 0.42370129 0.98487193]
 [0.5774839  0.87566373 0.96453277 0.41362664 0.61871835 0.04800806
  0.15949006

In [ ]:
#42. How do you find the closest value to a given scalar in an array?

a=np.array([1,2,3,4,5,75,78,40,50])
t=10
print(a)
index=a[np.abs(a-t).argmin()]
print(index)



[ 1  2  3  4  5 75 78 40 50]
5


In [ ]:
#43. How do you create a structured array with position and color fields?
a=np.zeros(10, [ ('position', [ ('x', int),('y', int)]),('color',    [ ('r', int),('g', int),('b', int)])])
print(a)

[((0, 0), (0, 0, 0)) ((0, 0), (0, 0, 0)) ((0, 0), (0, 0, 0))
 ((0, 0), (0, 0, 0)) ((0, 0), (0, 0, 0)) ((0, 0), (0, 0, 0))
 ((0, 0), (0, 0, 0)) ((0, 0), (0, 0, 0)) ((0, 0), (0, 0, 0))
 ((0, 0), (0, 0, 0))]


In [ ]:
#44. How do you compute pairwise distances between coordinates?
x=np.array([[0,0],[0,1],[1,0],[1,1])
from scipy.spatial import distance
D = distance.cdist(x, x,'euclidean')
print(D)

[[0.         1.         1.         1.41421356]
 [1.         0.         1.41421356 1.        ]
 [1.         1.41421356 0.         1.        ]
 [1.41421356 1.         1.         0.        ]]


In [ ]:
#45. How do you cast a float array to integer type in place?
a = np.array([1.5, 2.7, 3.9], dtype=np.int32)
print(a)
print(a.dtype)

[1 2 3]
int32


In [ ]:
#46. How do you read data from a file with missing values?


In [ ]:
#47. How do you iterate through all elements in a NumPy array with indices?
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
for index,value in np.ndenumerate(a):
    print(index,value)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(2, 0) 7
(2, 1) 8
(2, 2) 9


In [ ]:
#48. How do you create a 2D Gaussian-like array?


In [ ]:
#49. How do you randomly place a specific number of elements in a 2D array?
Z = np.zeros((10, 10))
Z.flat[np.random.choice(Z.size, 10, replace=False)] = 1
print(Z)

[[0. 0. 1. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 1. 0. 0. 0.]]


In [ ]:
#50. How do you subtract the row mean from a matrix?
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(a-a.mean(axis=1,keepdims=True))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


In [ ]:
#51. How do you sort a 2D array based on the values of one column?
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(a[a[:,1].argsort()])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#52. How do you check if a 2D array contains any null (zero-only) columns?
Z = np.array([
    [0, 1, 0],
    [0, 0, 0],
    [0, 5, 0]
])

null_columns = np.all(Z == 0, axis=0)

print(null_columns)

[ True False  True]


In [ ]:
#53. How do you find the nearest value to a given number in a NumPy array?
a=np.array([1,2,3,4,5,75,78,40,50])
t=10
print(a)
index=a[np.abs(a-t).argmin()]
print(index)

[ 1  2  3  4  5 75 78 40 50]
5


In [ ]:
#54. How do you create a NumPy subclass with custom attributes?
import numpy as np

In [ ]:
#55. How do you increment elements in an array using an index array with repeats?
a = np.zeros(5, dtype=int)
index = np.array([0, 1, 1, 3, 4])
np.add.at(a, index, 1)
print(a)

[1 2 0 1 1]


In [ ]:
#56. How do you accumulate values into an array based on indices?
a = np.zeros(5, dtype=int)
index = np.array([0, 1, 1, 3, 4])
values = np.array([10, 20, 30, 40, 50])
np.add.at(a, index, values)

print(a)


[10 50  0 40 50]


In [2]:
#57. How do you count unique colors in a 3D image array?



array([[14.74936664, 14.88602935, 13.19950935, 13.61114489],
       [12.21153188, 12.41600776, 16.02041151, 15.16210233],
       [15.45217618, 15.64560711, 14.55857957, 13.35143197]])

In [5]:
#58. How do you compute the sum across the last two axes of a 4D array?
a= np.random.rand(2, 3, 4, 5)
result = np.sum(a, axis=(-2, -1))

print(result.shape)
print(result)

(2, 3)
[[10.4395643   7.75312756 10.79550983]
 [ 9.27739276 10.52850523  9.97785848]]


In [6]:
#59. How do you calculate means of grouped values in an array?
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(a.mean())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
5.0


In [8]:
#60. How do you efficiently get the diagonal of a matrix dot product?
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(b)
diagonal = np.einsum("ij,ji->i", a, b.T)

print(diagonal)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 14  77 194]


In [9]:
#61. How do you interleave a vector with a fixed number of zeros?
A = np.random.rand(5,5)
B = np.random.rand(5,5)
np.einsum("ii->i", np.dot(A, B))

array([1.4285883 , 1.00120882, 1.29434651, 0.67438954, 1.60368308])

In [17]:
#62. How do you multiply a (5,5,3) array with a (5,5) array element-wise?

a1=np.random.rand(5,5,3)
a2=np.random.rand(5,5)

result = a * b[:, :, np.newaxis]
print(result)

[[[ 1  2  3]
  [ 8 10 12]
  [21 24 27]]

 [[ 4  8 12]
  [20 25 30]
  [42 48 54]]

 [[ 7 14 21]
  [32 40 48]
  [63 72 81]]]


In [18]:
#63. How do you swap two rows in a matrix?
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
a[[0,1]]=a[[1,0]]
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[4 5 6]
 [1 2 3]
 [7 8 9]]


In [ ]:
#64. How do you extract unique line segments from triangle definitions?
a=

In [19]:
#65. How do you recreate an array from a bincount?
a=np.array([1,2,3,4,5,75,78,40,50])
t=np.bincount(a)
reconstructed = np.repeat(np.arange(len(t)), t)
print("Reconstructed array:", reconstructed)

Reconstructed array: [ 1  2  3  4  5 40 50 75 78]


In [22]:
#66. How do you compute a moving average using a sliding window?
from numpy.lib.stride_tricks import sliding_window_view

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
size = 3

windows = sliding_window_view(a, window_shape=size)

avg = windows.mean(axis=1)

print(avg)

[2. 3. 4. 5. 6. 7. 8.]


In [23]:
#67. How do you create a rolling 2D view from a 1D array?
import numpy as np
from numpy.lib.stride_tricks import sliding_window_view

a = np.array([0, 1, 2, 3, 4, 5, 6])

size = 3

result = sliding_window_view(a, window_shape=size)

print(result)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]


In [24]:
#68. How do you invert booleans or negate floats in-place?
a = np.array([True, False, True, True])
a[:] = ~a

print(a)

[False  True False False]


In [ ]:
#69. How do you compute the distance from a point to multiple lines?


In [ ]:
#70. How do you compute the distances from multiple points to multiple lines?


In [25]:

#71. How do you extract a fixed-shaped subarray centered on a given point?

a = np.arange(100).reshape(10, 10)
center = (4, 4)
size = (3, 3)
half_h = size[0] // 2
half_w =size[1] // 2

i, j = center
subarray = a[i - half_h:i + half_h + 1, j - half_w:j + half_w + 1]

print(subarray)

[[33 34 35]
 [43 44 45]
 [53 54 55]]


In [1]:
#72. How do you generate overlapping subarrays from a vector?
import numpy as np
from numpy.lib.stride_tricks import sliding_window_view

# Original vector
a = np.array([1, 2, 3, 4, 5, 6, 7])

# Window size
window_size = 3

# Generate overlapping subarrays
windows = sliding_window_view(a, window_shape=window_size)

print(windows)

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]]


In [2]:
#73. How do you compute the rank of a matrix using SVD?
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
u, s, vh = np.linalg.svd(a)
rank = np.sum(s > 1e-10)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
#74. How do you find the most frequent value in an array?
a=np.array([1,2,3,3,7,8,2,3,4,5,75,78,40,50])
print(a)
print(np.bincount(a).argmax())

[ 1  2  3  3  7  8  2  3  4  5 75 78 40 50]
3


In [5]:
#75. How do you extract all 3x3 contiguous blocks from a 10x10 matrix?
a=np.random.rand(10,10)
print(a)
print(np.lib.stride_tricks.sliding_window_view(a, (3, 3)))

[[0.12723462 0.09364219 0.40092969 0.06047572 0.04208155 0.34334078
  0.58748394 0.65503291 0.88840215 0.14862765]
 [0.50225876 0.62096964 0.7442107  0.63761883 0.59601648 0.85785651
  0.45685523 0.4463365  0.99610714 0.11417901]
 [0.64104632 0.71498615 0.39419374 0.10552404 0.4114591  0.87646666
  0.65406885 0.95993963 0.4572251  0.18702655]
 [0.01232533 0.29477927 0.63491334 0.34206495 0.66132396 0.14390075
  0.04815413 0.65465437 0.14996798 0.98059344]
 [0.16084541 0.78187421 0.43200769 0.97528439 0.80203974 0.63771474
  0.12349675 0.72226389 0.89771703 0.92528622]
 [0.75182166 0.67076085 0.72701137 0.02759201 0.38382746 0.35708729
  0.25544571 0.78988144 0.24926996 0.48617743]
 [0.98774673 0.69353002 0.88562724 0.15673618 0.60475857 0.22864821
  0.17320604 0.57090458 0.87551264 0.02939206]
 [0.29461575 0.78112656 0.69012455 0.52775763 0.65021571 0.99980235
  0.57336514 0.66577255 0.56078688 0.11521884]
 [0.24024048 0.86833635 0.34151655 0.89066177 0.05806274 0.8407263
  0.32769886 

In [6]:
#76. How do you create a 2D symmetric matrix class?
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(a.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [7]:
#77. How do you compute the sum of multiple matrix-vector products at once?
a = np.random.rand(5, 3, 4)

x = np.random.rand(5, 4)

result = np.einsum('ijk,ik->ij', a, x)
sum_result = np.sum(result, axis=0)

print("Sum of all A_i @ x_i:", sum_result)

Sum of all A_i @ x_i: [4.02612941 3.71767397 5.37463419]


In [8]:
#78. How do you compute the sum of blocks in a 2D array?
a = np.arange(64).reshape(8, 8)
block_h, block_w = 2, 2
blocks = a.reshape(
    a.shape[0] // block_h, block_h,
    a.shape[1] // block_w, block_w
)
block_sums = blocks.sum(axis=(1, 3))

print(block_sums)

[[ 18  26  34  42]
 [ 82  90  98 106]
 [146 154 162 170]
 [210 218 226 234]]


In [ ]:
#79. How do you simulate the Game of Life using NumPy?


In [9]:
#80. How do you extract the top N largest values from an array?

a = np.array([10, 50, 20, 80, 40, 90, 70])
N = 3
top_n_unsorted = np.partition(a, -N)[-N:]
top_n_sorted = np.sort(top_n_unsorted)[::-1]

print("Top N values:", top_n_sorted)

Top N values: [90 80 70]


In [11]:
#81. How do you create a Cartesian product of multiple input arrays?
a = np.array([1, 2])
b = np.array([3, 4])
c = np.array([5, 6])

grid = np.meshgrid(a, b, c, indexing='ij')

# Stack and reshape to get Cartesian product
product = np.stack(grid, axis=-1).reshape(-1, 3)

print(product)

[[1 3 5]
 [1 3 6]
 [1 4 5]
 [1 4 6]
 [2 3 5]
 [2 3 6]
 [2 4 5]
 [2 4 6]]


In [13]:
#82. How do you create a record array from a regular NumPy array?
a = np.array([(1, 'Alice', 25), (2, 'Bob', 30), (3, 'Charlie', 22)])
record_a = np.core.records.fromarrays(a.T, names='id, name, age')

print(record_a)

[('1', 'Alice', '25') ('2', 'Bob', '30') ('3', 'Charlie', '22')]


/tmp/ipython-input-13-851208783.py:3: DeprecationWarning: numpy.core is deprecated and has been renamed to numpy._core. The numpy._core namespace contains private NumPy internals and its use is discouraged, as NumPy internals can change without warning in any release. In practice, most real-world usage of numpy.core is to access functionality in the public NumPy API. If that is the case, use the public NumPy API. If not, you are using NumPy internals. If you would still like to access an internal attribute, use numpy._core.records.
  record_a = np.core.records.fromarrays(a.T, names='id, name, age')


In [17]:
#83. How do you raise an array to the power of 3 using different methods?
a=np.arange(10)
print(a)
a_cubed = a ** 3
print(a_cubed)

[0 1 2 3 4 5 6 7 8 9]
[  0   1   8  27  64 125 216 343 512 729]


In [19]:
#84. How do you find rows in a matrix containing all elements of another matrix?
import numpy as np
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([4, 5, 6])

matches = np.array([np.all(np.isin(B, row)) for row in A])
result = A[matches]

print("Matching rows:\n", result)

Matching rows:
 [[4 5 6]]


In [20]:
#85. How do you filter rows in a matrix with at least one differing value?
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
ref = np.array([1, 2, 3])
mask = np.any(A != ref, axis=1)

different_rows = A[mask]

print( different_rows)

[[4 5 6]
 [7 8 9]]


In [22]:
#86. How do you convert integers to their binary matrix representation?
a=np.array([1,2,3,4,5,75,78,40,50])
print(a)
print(np.unpackbits(a.astype(np.uint8)[:, np.newaxis], axis=1))

[ 1  2  3  4  5 75 78 40 50]
[[0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0 1]
 [0 1 0 0 1 0 1 1]
 [0 1 0 0 1 1 1 0]
 [0 0 1 0 1 0 0 0]
 [0 0 1 1 0 0 1 0]]


In [24]:
#87. How do you extract unique rows from a 2D array?
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
unique_rows = np.unique(a, axis=0)
print(unique_rows)

[[1 2 3]
 [4 5 6]
 [8 8 9]]
[[1 2 3]
 [4 5 6]
 [8 8 9]]


In [ ]:
#88. How do you compute inner, outer, sum, and multiplication using einsum?



In [ ]:
#89. How do you sample a 2D path at regular intervals?


In [25]:
#90. How do you filter 2D array rows that sum to a specific number using only integers?
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(a[a.sum(axis=1) == 10])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[]


In [26]:
#91. How do you vertically and horizontally stack two arrays?
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
v_stacked = np.vstack((a, b))
h_stacked = np.hstack((a, b))

print( v_stacked)
print( h_stacked)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [27]:
#92. How do you apply a custom function to each element of an array?
a = np.array([1, 2, 3, 4, 5])
def custom_func(x):
    return x**2 + 1
v= np.vectorize(custom_func)

# Apply it
result = v(a)
print(result)

[ 2  5 10 17 26]


In [29]:
#93. How do you remove duplicate rows in a 2D array?
a=np.array([[1,2,3],[4,5,6],[7,8,9]])

unique_rows = np.unique(a, axis=0)
print(unique_rows)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [30]:
#94. How do you filter rows based on a specific column value?
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(a[a[:, 1] > 5])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[7 8 9]]


In [32]:
#95. How do you find column-wise and row-wise minimum/maximum indices?
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(np.argmax(a, axis=0))
print(np.argmax(a, axis=1))


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 2 2]
[2 2 2]


In [35]:
#96. How do you replace NaN values in an array with the column mean?
a=np.array([[1,2,np.nan],[4,np.nan,6],[7,8,9]])
col_means = np.nanmean(a, axis=0)
inds = np.where(np.isnan(a))
a[inds] = np.take(col_means, inds[1])

print(a)

[[1.  2.  7.5]
 [4.  5.  6. ]
 [7.  8.  9. ]]


In [36]:
#97. How do you flatten and sort a 2D array?
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(np.sort(a.flatten()))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [37]:
#98. How do you calculate the correlation coefficient between two vectors?
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])
correlation = np.corrcoef(a, b)[0, 1]

In [38]:
#99. How do you extract the top-K values along a specific axis?
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(np.partition(a, 2, axis=0))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [39]:
#100. How do you detect outliers in a dataset using IQR?
data = np.array([10, 12, 14, 15, 18, 21, 22, 24, 29, 100])
Q1 = np.percentile(data, 25)
Q3 = np.percentile(data, 75)
IQR = Q3 - Q1
l = Q1 - 1.5 * IQR
u = Q3 + 1.5 * IQR

outliers = data[(data < l) | (data > u)]
print(outliers)


[100]


In [40]:
#101. How do you perform one-hot encoding using NumPy?
labels = np.array([0, 2, 1, 3])
num_classes = np.max(labels) + 1
one_hot = np.eye(num_classes)[labels]
print(one_hot)

[[1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]]


In [41]:
#102. How do you find the shape and number of elements in an array?
a=np.arange(10)
print(a.shape)
print(a.size)

(10,)
10


In [46]:
#103. How do you reshape an array without changing its data?
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
reshaped = a.reshape(3,4)
print(reshaped)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [48]:
#104. How do you flatten a multi-dimensional array?
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
flat = a.flatten()
print(flat)

[1 2 3 4 5 6 7 8 9]


In [49]:
#105. How do you get the cumulative sum along an axis?
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(a.cumsum(axis=0))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]


In [50]:
#106. How do you compute element-wise maximum/minimum of two arrays?
a = np.array([1, 5, 3])
b = np.array([3, 2, 4])
max= np.maximum(a, b)
print( max)

[3 5 4]


In [52]:
#107. How do you broadcast arrays with different shapes?
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([10, 20, 30])
result = a + b
print(result)


[[11 22 33]
 [14 25 36]]


In [53]:
#108. How do you transpose a matrix and perform dot products?
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(a.T)
print(a.dot(a.T))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[ 14  32  50]
 [ 32  77 122]
 [ 50 122 194]]


In [58]:
#109. How do you check for NaN or infinite values in an array?
a = np.array([1, 2, np.nan, np.inf, 3])
b=np.isnan(a)
c=np.isinf(a)
print(b)
print(c)

[False False  True False False]
[False False False  True False]


In [59]:
#110. How do you extract diagonal, upper, and lower triangles from a matrix?
a=np.array([[1,2,3],[4,5,6,],[7,8,9]])
d=np.diag(a)
t=np.triu(a)
l=np.tril(a)
print(d)
print(t)
print(l)

[1 5 9]
[[1 2 3]
 [0 5 6]
 [0 0 9]]
[[1 0 0]
 [4 5 0]
 [7 8 9]]
